---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python2
    me: dflemstr
    my_name: David Flemström
  tasks:
    - include: task/pacman.yaml
    - include: task/network.yaml
    - include: task/ssh.yaml
    - include: task/users.yaml
    - include: task/git.yaml
    - include: task/zsh.yaml
    - include: task/aur.yaml
    - include: task/sudo.yaml
    - include: task/fonts.yaml
    - include: task/xorg.yaml
    - include: task/gnome.yaml
    - include: task/docker.yaml
    - include: task/helios.yaml
    - include: task/vpn.yaml
    - include: task/packages.yaml
    - include: task/emacs.yaml
